const member = [
  {
    Firstname: "hamidreza",
    Lastname: "hosseini",
    NationalCode: 11111111,
    Gender: "Male",
    Orders: [
      {
        Product: "staminofen",
        Number: 5,
      },
    ],
    Employee: {
      PersonalCode: 12345678,
      Role: "doctor",
      Cals: [
        {
          starttime: 12,
          finishtime: 20,
          Date: "12/12/2022",
        },
      ],
    },
  },
  {
    Firstname: "ahmad",
    Lastname: "hamidi",
    NationalCode: 11111111,
    Gender: "Male",
    Orders: [
      {
        Product: "staminofen",
        Number: 2,
      },
    ],
    Employee: {
      PersonalCode: 12345678,
      Role: "Worker",
      Cals: [
        {
          starttime: 10,
          finishtime: 20,
          Date: "11/12/2023",
        },
      ],
    },
  },
];
